
SELECT CITY
FROM STATION
WHERE (LOWER(CITY) LIKE 'i%' 
OR LOWER(CITY) LIKE 'a%' 
OR LOWER(CITY) LIKE 'e%' 
OR LOWER(CITY) LIKE 'u%' 
OR LOWER(CITY) LIKE 'o%') AND 
(LOWER(CITY) LIKE '%i' 
OR LOWER(CITY) LIKE '%a' 
OR LOWER(CITY) LIKE '%e' 
OR LOWER(CITY) LIKE '%u' 
OR LOWER(CITY) LIKE '%o');
